### ISSUE TITLE
Equivalence check error

### ISSUE THREAD

**Issue by Qutcoder** [shrBadihi/ARDiff_Equiv_Checking#6]
Hello, there was an error when I checked the equivalence of the following two identical programs：
```
public class oldV {
    static final int[] primes = { 2, 3, 5, 7, 11, 13, 17, 19 };
    public static double snippet(int x) {
        return lib(x, 0);
    }
    public static double lib(int x, int b) {
        if (b == 0) {
            return 0;
        } else {
            for (int i = 0; i < 8; i++) {
                int mod = x % primes[i];
                if (mod == 0)
                    return x == primes[i];
            }
        }
        return 1;
    }
}
```
```
public class newV {
    static final int[] primes = { 2, 3, 5, 7, 11, 13, 17, 19 };
    public static double snippet(int x) {
        return lib(x, 0);
    }
    public static double lib(int x, int b) {
        if (b == 0) {
            return 0;
        } else {
            for (int i = 0; i < 8; i++) {
                int mod = x % primes[i];
                if (mod == 0)
                    return x == primes[i];
            }
        }
        return 1;
    }
}
```

An error/exception occurred when identifying the changes between the two methods.
The GumTree module is still under development. Please check your examples or report this issue to us.

java.io.IOException: Compilation error: Compilation error: illegal start of type';' expected']' expected';' expectedillegal start of type<identifier> expected';' expectedillegal start of type<identifier> expected<identifier> expectedillegal start of type<identifier> expected<identifier> expectedillegal start of type<identifier> expected<identifier> expectedillegal start of type<identifier> expected';' expected
        at equiv.checking.Utils.compile(Utils.java:69)
        at equiv.checking.ChangeExtractor.modifyFiles(ChangeExtractor.java:294)
        at equiv.checking.ChangeExtractor.obtainChanges(ChangeExtractor.java:61)
        at GradDiff.GradDiff.runTool(GradDiff.java:72)
        at Runner.Runner.runTool(Runner.java:163)
        at Runner.Runner.main(Runner.java:472)
        
Could you please confirm or point out my usage problem? Thank you very much.

**Comment by shrBadihi** [comment]
Hello,

The error is due to the change extractor function (which is based on GumTree). Since there are no syntactic changes between the two programs the results from GumTree are null. As equivalence checking for the case where there are no syntactic changes is trivial, we did not check for that. We will add an edge case check where the inputs are identical. 
Can you please modify one of the classes and then check again? For example, you can start by changing the following piece:
  if (b == 0) {
            **return 0; ====> return 1;**
  }

Thanks.

**Comment by Qutcoder** [comment]
I modified according to your prompt, and it was successful. Thank you
