### ISSUE TITLE
Running example failed on NullPointerException

### ISSUE THREAD

**Issue by cervoliu** [shrBadihi/ARDiff_Equiv_Checking#7]
@shrBadihi @dah-fari7009 
I have followed the instructions in `README.md` but got this when running the example:
```
 ➜  Implementation git:(master) ✗ time timeout 300 java -jar target/artifacts/Implementation_jar/Implementation.jar --path1 ../benchmarks/Airy/MAX/Eq/oldV.java --path2 ../benchmarks/Airy/MAX/Eq/newV.java --tool A
Arguments:
--path1 path/to/the/first/method --path2 path/to/the/second/method --tool ToolName --s SMTSolverName --t timeout --b bound --minint minInt --maxint maxInt --mindouble minDouble --maxdouble maxDouble
*****************
--tool ToolName: to choose the tool to run (Default is ARDiff):
--tool D: Run DSE
--tool I: Run IMP-S
--tool A: Run ARDiff
--t timeout: to choose the timeout for constraint solving in millisecond (Default is 300000 MS):
*****************
--b bound: to choose the loop bound (Default is 5)
*****************
--minint: the minimum value of integers in the program (Default is -100):
*****************
--maxint: the maximum value of integers in the program (Default is 100):
*****************
--mindouble: the minimum value of doubles in the program (Default is -100.0):
*****************
--maxdouble: the maximum value of doubles in the program (Default is 100.0):
*****************
--H: the heuristics for ARDiff (R,H3 or H123)
*****************
[NOTE] If you want to have a complete summary (exercise all behaviors), make sure your bound is big enough.
*****************************************************************************
------------------------------------ARDIFF-----------------------------------
*****************************************************************************
An error/exception occurred when identifying the changes between the two methods.
The GumTree module is still under development. Please check your examples or report this issue to us.


java.lang.NullPointerException
        at equiv.checking.Utils.compile(Utils.java:57)
        at equiv.checking.ChangeExtractor.modifyFiles(ChangeExtractor.java:294)
        at equiv.checking.ChangeExtractor.obtainChanges(ChangeExtractor.java:61)
        at GradDiff.GradDiff.runTool(GradDiff.java:72)
        at Runner.Runner.runTool(Runner.java:163)
        at Runner.Runner.main(Runner.java:472)
timeout 300 java -jar target/artifacts/Implementation_jar/Implementation.jar   2.07s user 0.29s system 308% cpu 0.765 total
```
What does it mean by "The GumTree module is still under development. Please check your examples or report this issue to us."?

**Comment by shrBadihi** [comment]
I saw that you are running the benchmark, but did you change the code of the example? GumTree is a tool we used for extracting changes between two programs.

**Comment by cervoliu** [comment]
@shrBadihi I didn't change the code of the example, i.e. `../benchmark/Airy/MAX/Eq/oldV.java` and `../benchmark/Airy/MAX/Eq/newV.java`, but still come across the issue above.
After running that prompt, the following files changed:

![image](https://github.com/user-attachments/assets/1e83ff8c-493b-41c4-879e-9c000af32dab)

I run this on Ubuntu 20.04, with Java version openjdk version "1.8.0_422"

**Comment by shrBadihi** [comment]
These files are intermediate files. The ubuntu version we tested before was 18.04.4. Are you getting the same error for all files?

**Comment by cervoliu** [comment]
Yes. I also tried running the benchmark testing script but all tests ends up the same error.

**Comment by shrBadihi** [comment]
Please try with ubuntu 18.04.4 or try it on Mac or Windows laptop.

**Comment by cervoliu** [comment]
@shrBadihi I tried it on Mac, now another issue appears.
![image](https://github.com/user-attachments/assets/31a2f310-3007-472c-bc8e-02d83eecde83)
It seems that the javaFX dependency is not correctly set up in build tool configuration files, but that's a different issue. Could you check this please?

**Comment by cervoliu** [comment]
After investigating further, I find the fact that JavaFX was not bundled with OpenJDK 8. Are you using Oracle's JDK? Switching the JDK version should resolve this issue.

**Comment by cervoliu** [comment]
I think the above NullPointerException issue is caused by JDK version mismatch. However, there is a new issue #8 after fixing these stuffs.

**Comment by Qi-Zhan** [comment]
> After investigating further, I find the fact that JavaFX was not bundled with OpenJDK 8. Are you using Oracle's JDK? Switching the JDK version should resolve this issue.

Hi, I've come up with the same issue: JavaFX is missing on Mac. Could you share the solution or which java you use? Thanks @cervoliu

**Comment by cervoliu** [comment]
@Qi-Zhan Oracle's JDK 8 should be fine. More specifically, the version is `oracle64-1.8.0.202` (tried on Ubuntu, but it should also work on Mac).
