### ISSUE TITLE
Running example error on reason "Error while running JPF-symbc"

### ISSUE THREAD

**Issue by cervoliu** [shrBadihi/ARDiff_Equiv_Checking#8]
![image](https://github.com/user-attachments/assets/07bd3613-1ffb-4072-9e33-52411d41a3f0)
Are there any additional changes to make in jpf-symbc?

**Comment by shrBadihi** [comment]
There is definitely an issue with your environment and setup. Please make sure you followed Readme and installed Z3 correctly.

**Comment by cervoliu** [comment]
I'm quite sure I followed the README file and installed z3 correctly(Actually z3 executable is included in the repository but I don't think it is a good idea). The dependency is poorly organized and there is neither instruction on how to build the project nor docker image provided. It only provides pre-built jar file which is quite confusing.

**Comment by shrBadihi** [comment]
As Z3 (or other solvers) are developing separately, to prevent any inconsistencies between the version that we used and newer versions, we included that in our repo. 
From the picture you provided I see that you do not have this in your command: -Djava.library.path=jpf-git/jpf-symbc/lib 
This is stated in README. In your case, jpf-symbc seems not finding Z3. Please let me know if including that fixes the issue.

**Comment by cervoliu** [comment]
I explicitly set the environment variable LD_LIBRARY_PATH to the correct directory, i.e. `.../jpf-git/jpf-symbc/lib` (absolute path), which would take the same effect as `-Djava.library.path=jpf-git/jpf-symbc/lib`. Nevertheless, I tried again with `-Djava.library.path`, but the issue is still there.

**Comment by shrBadihi** [comment]
Do you get error for other examples as well?

**Comment by cervoliu** [comment]
Yes. Again, I run the script that test the benchmark and get the same error (Error while running JPF-symb).

**Comment by shrBadihi** [comment]
We tried installing ARDiff on fresh Machines (linux, OS X, and windows) and did not have this error. There were also a set of users so far that installed and ran the tool. So without extra information I cannot debug the error further. I would suggest to try installing on Ubuntu 18.04.4 as different versions of OS X could also behave differently.

**Comment by cervoliu** [comment]
Thank you, I will try it later.

**Comment by cervoliu** [comment]
Month later, I just tried once again from the very beginning and finally found the cause of the problem.
The irredeemably stupid parsing logic of the `site.properties` file required by Java Pathfinder is all to blame.
In my previous attempts, the "extensions" setting in my `site.properties` file looks like this:
```
extensions = ${jpf-core}, ${jpf-symbc}
```
It seems to be normal, but there's a subtle mistake that **a redundant space** is between the two extensions, which makes jpf ignore the latter one, i.e. jpf-symbc. All you need to fix is to remove that space:
```
extensions = ${jpf-core},${jpf-symbc}
```

**Comment by Qi-Zhan** [comment]
Another
I've come up with the same situation, too. After many times try😂, I find that you **must** use the absolute path in `site.properties` file and it finally works!
